### ISSUE TITLE
Angular 2, Problem in navigating from google chart to other component by click handler

### ISSUE THREAD

**Issue by ptech360** [platosha/angular-polymer#139] opened 2017-03-17 12:44 UTC
I have a problem in loading data when navigating from google chart to other component of the application. It is navigating but waiting for mouse move to load data on the html.

**Comment by BorntraegerMarc** [comment] 2017-03-17 13:02
@ptech360 could you provide some code that we could actually review this problem?

**Comment by ptech360** [comment] 2017-03-17 13:19
I have a directive named *chart.directive.ts*
I am using it in a component named *home.component.ts* my project to draw
google charts. I used click event listener for navigating to other
component named *complaint.list.ts .*
it navigate easily but after navigating it wait for a mouse move to load
data on corresponding html page named complaint.list.html

**Comment by BorntraegerMarc** [comment] 2017-03-17 13:24
Can you provide a plunker or something? Because I'm not able to reproduce the problem

**Comment by BorntraegerMarc** [comment] 2017-03-27 16:29
Closing until @ptech360 is providing more info.

**Closed as completed by BorntraegerMarc** 2017-03-27 16:29 UTC
