### ISSUE TITLE
two-way binding paper-input

### ISSUE THREAD

**Issue by brOOper** [platosha/angular-polymer#49] opened 2016-07-22 14:14 UTC
The two way databinding does seem to work only in one direction. The value gets set on the paper-input but when changing, the model field (`customer.firstname` in this case) is not being updated.

``` html
<paper-input [(value)]="customer.firstname" label="Firstname"></paper-input>
```

(Version v1.0.0-beta2)

**Comment by Saulis** [comment] 2016-08-01 08:13
Hi!

Tried reproducing with

``` html
<label>{{model.foobar | json}}</label>
<input type="text" [value]="model.foobar" (input)="model.foobar=$event.target.value">
<paper-input [(value)]="model.foobar"></paper-input>
```

And everything seems to update like it should. Have you remembered to add `PolymerElement('paper-input')` directive? 

If still not working, could provide a full example where the problem occurs? Thanks!

**Comment by florent1933** [comment] 2016-08-03 10:18
Same problem: 

This one is working [value]="model.foobar" (input)="model.foobar=$event.target.value"

but not: 
- [(value)]="model.foobar"
- [(ngModel)]="model.foobar"

Stacktrace for  [(ngModel)], seems to be related https://github.com/vaadin/angular2-polymer/issues/41: 
`ORIGINAL EXCEPTION: No value accessor for ''BrowserDomAdapter.logError @ browser_adapter.ts:82
browser_adapter.ts:82 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:82
browser_adapter.ts:82Error: No value accessor for ''
    at new BaseException (exceptions.ts:21)
    at _throwError (shared.ts:66)
    at Object.setUpControl (shared.ts:38)
    at NgModel.ngOnChanges (ng_model.ts:42)
    at DebugAppView._View_IndexSearchComponent0.detectChangesInternal (IndexSearchComponent.template.js:250)
    at DebugAppView.AppView.detectChanges (view.ts:261)
    at DebugAppView.detectChanges (view.ts:377)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:288)
    at DebugAppView._View_IndexComponent0.detectChangesInternal (IndexComponent.template.js:166)
    at DebugAppView.AppView.detectChanges (view.ts:261)BrowserDomAdapter.logError @ browser_adapter.ts:82
browser_adapter.ts:82ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.ts:82
browser_adapter.ts:82DebugContext`

Angular : 2.0.0-rc.4

**Comment by brOOper** [comment] 2016-08-03 20:42
I put the directive `PolymerElement('paper-input')` in the parent component so I have to put it only once. Moving it to the component where it is used made it work. 

@Saulis Why can't I just put it on the parent component like other directives?

**Comment by florent1933** [comment] 2016-08-04 08:30
@brOOper : Do you have two way data binding with: 
- [(value)]="model.foobar"
- [(ngModel)]="model.foobar" ?

**Comment by platosha** [comment] 2016-08-23 11:38
Is it that you are using the Angular’s New Forms module? If so, this should be fixed by #55. Please try again with the master version of `@vaadin/angular2-polymer`.

**Comment by oravecz** [comment] 2016-09-16 02:19
It seems that the newer versions of Angular2 are incompatible with the `PolymerElement()` call. Without that function to wire up 2-way data binding, what is an alternative?

 #84

**Comment by platosha** [comment] 2016-09-16 07:47
We can’t reproduce the original issue, closing.

@oravecz We don’t have an answer yet. Looks like you are facing the same issue as in #86, so let us continue there.

**Closed as completed by platosha** 2016-09-16 07:47 UTC

**Comment by oravecz** [comment] 2016-09-16 21:24
As long as I add the `PolymerElement(...)` to NgModule, and _not_ to the component, then all works as expected.

```
declarations: [
        AppComponent,
        PolymerElement( 'paper-input' )
]
```

**Comment by niveo** [comment] 2016-09-21 20:56
this don't works

```
<paper-radio-group [(selected)]="model.select">
     <paper-radio-button name="1">yes</paper-radio-button>
     <paper-radio-button name="0">no</paper-radio-button>
</paper-radio-group>
```
